name: ZooCraft
version: ${project.version}
main: com.elwarriorcito.plugins.zoocraft.core.ZooCraft
api-version: 1.16
authors: [ ElWarriorcito, AlPaSa, ProGamer ]
description: A Zoo plugin for a Minecraft server
commands:
  getGoldCrop:
    aliases: [getcrop, items, goldenCrop, gc]
  getCropInfo:
    aliases: [cropInfo, plantedCrops, pc, ci]
  getTaskIdInfo:
    aliases: [taskid, cropid, infoid]