name: ZooCraft
version: ${project.version}
main: com.elwarriorcito.plugins.zoocraft.ZooCraft
api-version: 1.16
authors: [ ElWarriorcito, AlPasa, ProGramer26000 ]
description: A Zoo plugin for a Minecraft server
